version: '3'
services:

    nginx:
      image: nginx:alpine
      build: ./docker/nginx
      ports:
          - "10050:80"
      depends_on:
          - php
      volumes:
          - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
          - ./laravel:/var/www/html
          - "phpsocket:/var/run"

    php:
      image: php:fpm-alpine
      build: ./docker/php-fpm
      volumes:
          - ./laravel:/var/www/html
          - ./docker/php-fpm/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
          - "phpsocket:/var/run"

    nuxt:
      image: node-express-dev:1.0
      build: ./docker/nuxt
      tty: true
      ports:
        - "3000:3000"
      volumes:
          - ./nuxt:/var/www/html/nuxt

volumes:
    phpsocket:
